spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: 
              - "http://localhost:*"
              - "https://localhost:*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: ms-requests
          uri: lb://ms-requests
          predicates:
            - Path=/api/v1/requests/**
          filters:
            - StripPrefix=0
        - id: ms-companies
          uri: lb://ms-companies
          predicates:
            - Path=/api/v1/companies/**, /api/v1/departments/**
          filters:
            - StripPrefix=0
        - id: ms-employees
          uri: lb://ms-employees
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - StripPrefix=0
        - id: ms-attendance
          uri: lb://ms-attendance
          predicates:
            - Path=/api/v1/attendances/**
          filters:
            - StripPrefix=0
        - id: ms-training
          uri: lb://ms-training
          predicates:
            - Path=/api/v1/tutorials/**
          filters:
            - StripPrefix=0
