services:
  ms-attendance:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Alonso1106
  ms-training:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Alonso1106
  ms-requests:
    image: mysql
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Alonso1106
  ms-auth:
    image: mysql
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Alonso1106
      - MYSQL_DATABASE=auth  